theme: jekyll-theme-minimal
# plugins: [jekyll-remote-theme, jekyll-include-cache]
# remote_theme: mmistakes/minimal-mistakes@4.26.2
title: Séverine Favre
description: Journaliste - Ingénieure Agronome
